### ISSUE TITLE
'More indentation included to distinguish this from the rest' doesn't work

### ISSUE THREAD

**Issue by kabanovdmitry** [hynek/vim-python-pep8-indent#22]
PEP8 says to add more indentation in such case:

```python
# More indentation included to distinguish this from the rest.
def long_function_name(
        var_one, var_two, var_three,
        var_four):
    print(var_one)
```

but when I use [vim-python-pep8-indent](https://github.com/hynek/vim-python-pep8-indent), I get the following:

```python
    def long_function_name(
    var_one, var_two, var_three,
        var_four):
        print(var_one)
```

I printed the code above manually, not pasted it.

**Comment by blueyed** [comment]
This seems to be the same as #30 (which has more examples), closing as duplicate.
