### ISSUE TITLE
Comments just after opening brackets are not ignored

### ISSUE THREAD

**Issue by lesguillemets** [hynek/vim-python-pep8-indent#32]
Like this : 

```python
mydict = {
    "this" : "is good"
}

mydict = { # comments
          "this" : "does not seem good"
          }
```

This is troublesome when one wants to use foldmarker with (e.g.) dictionaries. 

Sorry I couldn't come up with any PR.

**Comment by blueyed** [comment]
Agreed.

The `nothing_after_opening_paren` would need to be improved to also ignore comments (https://github.com/hynek/vim-python-pep8-indent/blob/25a499c3a6c1c89f96e906a197cdc6939a8e309e/indent/python.vim#L148).

This could be refactored to use the same behaviour as for the "colon check" (improved in https://github.com/hynek/vim-python-pep8-indent/pull/41).

**Comment by blueyed** [comment]
This should be fixed now.

Thanks for the report!

**Comment by lesguillemets** [comment]
:+1: Thank you!
