### ISSUE TITLE
opening `{{` in triple quotes causes havoc

### ISSUE THREAD

**Issue by oryband** [hynek/vim-python-pep8-indent#33]
I guess this is as intended, so it could be easier to write dicts in quotes. But sometimes it isn't wanted. Any way this can be disabled just for a single line?

**Comment by blueyed** [comment]
Is this still a problem?
Can you provide an example with the current and expected behaviour, please?

**Comment by oryband** [comment]
this issue was opened 6 months ago, and i received no response since then. I don't remember. You're welcome to try to recreate or close, I won't be getting into this anytime soon.

**Comment by blueyed** [comment]
I see.
I am closing it for now then.
