### ISSUE TITLE
Improve alignment inside of (multiline) strings

### ISSUE THREAD

**Issue by blueyed** [hynek/vim-python-pep8-indent#36]
After a line like the following, indenting is aligned at the opening parenthesis:

    django_testdir.create_test_module('''

This even happens when there are lines in the string already:

    django_testdir.create_test_module('''
        import sys

At least in the second case, the previous line should be used for indenting.

The syntax highlighting group is `pythonString` in this case - maybe this could be used to behave differently?!

**Comment by hynek** [comment]
Yeah this is annoying.  Within `'''` and `"""` groups should be no auto-indent whatsoever.

**Comment by blueyed** [comment]
> Within `'''` and `"""` groups should be no auto-indent whatsoever.

I think it whould be indented by one level, shouldn't it?

I am fixing the existing PR now, and will add some test.

**Comment by hynek** [comment]
No, unless it’s a docstring, it’s literal strings so any indentation would have to be removed by hand.

Does pep8 say anything about that?

**Comment by blueyed** [comment]
> Does pep8 say anything about that?

I don't know.

> it’s literal strings so any indentation would have to be removed by hand.

With pytest it's common practice to use `dedent` (`from textwrap import dedent`) for these strings.

**Comment by blueyed** [comment]
I've updated the PR, and changed it to use indent=0 by default.

It fails for the following now:

    foo(""<CR>

It should get aligned with the paren, but isn't.

A problem here is that the syntax highlighting does not distinguish between single/multi-line strings, which might help in this case.

I've thought about using `searchpairs`, but that does not work with quotes propbably?!

**Comment by blueyed** [comment]
Another set of updates in the PR: https://github.com/hynek/vim-python-pep8-indent/pull/37

Please review it from there.

**Comment by blueyed** [comment]
Closing this in favor of #37.
