### ISSUE TITLE
Does anyone can tell me how to use this to format the code?

### ISSUE THREAD

**Issue by scymen** [hynek/vim-python-pep8-indent#43]
I've installed vim-pthon-pep8-indent with bundle, 

I've ran  :pep8 in VIM but got nothing.

how to use it? thanks.

**Comment by blueyed** [comment]
It will/should be used for indenting automatically, by setting up `indentexpr` (see Vim's help on that).

Make sure to add/have the following in your vimrc, which should be there already, when using plugins:

    filetype plugin indent on

`:pep8` should result in an error, doesn't it?

**Comment by scymen** [comment]
Thank you for your reply, I should try these.

**Comment by blueyed** [comment]
If you feel that the documentation could be improved (I think so), please consider providing a PR for it.
