### ISSUE TITLE
unexpected indent after a line with list slice

### ISSUE THREAD

**Issue by linuxlc** [hynek/vim-python-pep8-indent#44]
my test cases:
```python
a = [1, 2, 3, 4, 5, 6]
a = 'abcdef'
b = a[2:]
    print b # invalid indent
c = a[:-2]
    print c # invalid indent
d = a[0:5:2]
    print d # invalid indent
```

**Comment by blueyed** [comment]
@linuxlc 
Is that with the version from master?
Because at least the first case is working for me.

**Comment by linuxlc** [comment]
@blueyed 
Yes, master branch with latest version.
The second line is not a case, by the way.

**Comment by blueyed** [comment]
Your test case gets indented to the following for me (`gg=G`):

    a = [1, 2, 3, 4, 5, 6]
    a = 'abcdef'
    b = a[2:]
    print b # invalid indent
    c = a[:-2]
    print c # invalid indent
    d = a[0:5:2]
    print d # invalid indent

This seems to be correct, isn't it?

What does `:verb set indentexpr?` give you?

**Comment by linuxlc** [comment]
@blueyed 
```
  indentexpr=GetPythonPEPIndent(v:lnum)
        Last set from ~/.vim/bundle/vim-python-pep8-indent/indent/python.vim
Press ENTER or type command to continue
```

**Comment by audriusk** [comment]
I'm experiencing the same bug as @linuxlc, it can be reproduced with dicts as well. Pressing `o` when cursor is on line
```python
foo = {'foo': 1}
```
leaves the new line indented when it shouldn't be.

And yes, this is on latest master.

**Comment by linuxlc** [comment]
@blueyed @audriusk 
I may have found the problem here, at indent/python.vim:246.
In previous version(before 7cb9a56c62d3540432cbcf78364569be19eb9e8a), the pattern is
```
':\s*\%(#.*\)\?$'
```
which means "a colon followed by nothing but comment", but in current version, the pattern is 
```
':'
```
which is not strict enough.
change the pattern to the old one seems to solve the problem.

**Comment by blueyed** [comment]
Yeah, you're right - I wasn't using the current master myself.. :/

I don't have time to look into this next days, so you might want to go back to an earlier commit for now.

**Comment by blueyed** [comment]
Sorry for the interruption, and thanks for the report(s).
It is fixed now.
