### ISSUE TITLE
Multiline strings are not indented properly

### ISSUE THREAD

**Issue by blueyed** [hynek/vim-python-pep8-indent#49]
I consider the following to be good:

```python
        testdir.makeini("""
            [pytest]
            paths=blah.py""")
```

But currently it becomes:

```python
        testdir.makeini("""
[pytest]
                        paths=blah.py""")
```

**Comment by blueyed** [comment]
I've started working on fixing it.

**Comment by hynek** [comment]
I don't think then lines after `"""` should be indented.  It forces the user to run dedent on it.

**Comment by blueyed** [comment]
> I don't think then lines after """ should be indented. It forces the user to run dedent on it.

It would keep manually indented lines: so you would dedent manually after `<cr>` and then lines after it would also be indented in the same way, e.g.:

There could also be an option for this behavior.

We agree though that the current behavior is just wrong, right? :)

**Comment by blueyed** [comment]
What behavior would you line to control?

Should be the indent after `test("""foo` controllable in a different way from `test("""`?
Would you like to have it being 0 for you in both cases?

**Comment by blueyed** [comment]
Added a setting for this - previous question still remains.  Currently the setting gets used regardless of if there is something after the opening `"""`.

**Comment by hynek** [comment]
yes i think there should be no difference.  `"""` are literal strings so I feel they should be as literal as possible by default. :)

**Comment by hynek** [comment]
you mean like:

```
foo = """
X
   abc
   Y
"""
```

- enter after `"""`, you end up at X
- enter after c, you wind up at Y

?

**Comment by blueyed** [comment]
@hynek 
Yes, that behavior will be kept.

But I've meant that when using `==` etc on a non-empty line that is in a multiline string, the existing indentation won't be changed.

**Comment by blueyed** [comment]
I've worked some more on #50 and think it should be good by now, please review it.
