### ISSUE TITLE
Line wrapping of strings while typing

### ISSUE THREAD

**Issue by languitar** [hynek/vim-python-pep8-indent#55]
I am not sure whether this is an issue this plugin should solve or whether the vim python rules are the origin of the issue.

When writing long strings in single or double quotes which go beyond `textwidth`, the string is automatically wrapped to a new line but without correct quoting rules, resulting in a broken python file. E.g. the following could be a result:

```python
foo.method('A long string which wraps after this
           and continues without new quotes')
```

Would be nice if this case could be handles so that the following is the result:
```python
foo.method('A long string which wraps after this '
           'and continues without new quotes')
```

**Comment by blueyed** [comment]
I think you should not set the `'wrap'` option for coding filetypes.
It makes sense with text filetypes (including "eml"), but not for coding.

Anyway, automatically adding quotes is out of scope for vim-python-pep8-indent.
