### ISSUE TITLE
'else' is not dedented in nested 'if' statements

### ISSUE THREAD

**Issue by audriusk** [hynek/vim-python-pep8-indent#56]
After 2c38ff0 commit writing `else:` in nested `if` statement doesn't dedent it automatically.

```python
if foo:
    if bar:
        baz = True
```
If we insert new line at the end of this block and start writing `else:`, it stays at the same indentation level as the line above:
```python
if foo:
    if bar:
        baz = True
        else:  # Should be dedented by one indentation level.
```

**Comment by blueyed** [comment]
Thanks for the report!

https://github.com/hynek/vim-python-pep8-indent/pull/59 should fix it.
